//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.22 at 09:48:02 PM EST 
//


package com.mikailapages.article_ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mikailapages.article_ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mikailapages.article_ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllArticlesRequest }
     * 
     */
    public GetAllArticlesRequest createGetAllArticlesRequest() {
        return new GetAllArticlesRequest();
    }

    /**
     * Create an instance of {@link GetArticleByIdResponse }
     * 
     */
    public GetArticleByIdResponse createGetArticleByIdResponse() {
        return new GetArticleByIdResponse();
    }

    /**
     * Create an instance of {@link ArticleInfo }
     * 
     */
    public ArticleInfo createArticleInfo() {
        return new ArticleInfo();
    }

    /**
     * Create an instance of {@link GetArticleByIdRequest }
     * 
     */
    public GetArticleByIdRequest createGetArticleByIdRequest() {
        return new GetArticleByIdRequest();
    }

    /**
     * Create an instance of {@link DeleteArticleRequest }
     * 
     */
    public DeleteArticleRequest createDeleteArticleRequest() {
        return new DeleteArticleRequest();
    }

    /**
     * Create an instance of {@link AddArticleResponse }
     * 
     */
    public AddArticleResponse createAddArticleResponse() {
        return new AddArticleResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link AddArticleRequest }
     * 
     */
    public AddArticleRequest createAddArticleRequest() {
        return new AddArticleRequest();
    }

    /**
     * Create an instance of {@link UpdateArticleResponse }
     * 
     */
    public UpdateArticleResponse createUpdateArticleResponse() {
        return new UpdateArticleResponse();
    }

    /**
     * Create an instance of {@link DeleteArticleResponse }
     * 
     */
    public DeleteArticleResponse createDeleteArticleResponse() {
        return new DeleteArticleResponse();
    }

    /**
     * Create an instance of {@link GetAllArticlesResponse }
     * 
     */
    public GetAllArticlesResponse createGetAllArticlesResponse() {
        return new GetAllArticlesResponse();
    }

    /**
     * Create an instance of {@link UpdateArticleRequest }
     * 
     */
    public UpdateArticleRequest createUpdateArticleRequest() {
        return new UpdateArticleRequest();
    }

}
